name: Test toolchain

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || github.ref }}

      - run: curl -s https://raw.githubusercontent.com/gocachedev/go/refs/heads/master/patches > patches
        shell: bash

      - run: go run github.com/uber-go/gopatch@v0.4.0 -p patches ./src
        shell: bash

      - name: test
        run: cd src && ./all.bash
        shell: bash
